# Generated by Django 2.2 on 2022-08-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='web_address',
            field=models.URLField(blank=True, verbose_name='web address'),
        ),
    ]
