# Generated by Django 2.2 on 2022-08-04 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0004_auto_20220804_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_planned', to=settings.AUTH_USER_MODEL),
        ),
    ]
