# Generated by Django 2.2 on 2022-08-04 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20220804_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='host',
            new_name='user',
        ),
    ]
