# Generated by Django 2.2 on 2022-08-04 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20220804_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='host',
        ),
    ]
