# Generated by Django 2.2 on 2022-08-08 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_venue_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='owner',
        ),
    ]
