# Generated by Django 2.2 on 2022-08-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_venue_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='event_notes',
            new_name='venue_notes',
        ),
    ]
