# Generated by Django 2.2 on 2022-08-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_auto_20220808_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_notes',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
