# Generated by Django 2.2 on 2022-08-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_auto_20220809_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_notes',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
