# Generated by Django 2.2 on 2022-07-19 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0002_auto_20220719_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
