# Generated by Django 2.2 on 2022-07-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0004_user_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_notes',
            field=models.TextField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
