# Generated by Django 2.2 on 2022-07-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0005_event_event_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
