# Generated by Django 2.2 on 2022-07-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0006_auto_20220720_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='private',
            field=models.BooleanField(),
        ),
    ]
