# Generated by Django 2.2 on 2022-07-24 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0009_auto_20220724_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
