# Generated by Django 2.2 on 2022-07-25 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0011_auto_20220724_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='event_planned', to=settings.AUTH_USER_MODEL),
        ),
    ]
