# Generated by Django 2.2 on 2022-07-25 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0012_auto_20220725_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
    ]
