# Generated by Django 2.2 on 2022-07-25 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0014_event_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_image',
            new_name='profile_img',
        ),
    ]
